apiVersion: v2
name: zero-trust-workload-identity-manager
description: Zero Trust Workload Identity Manager Helm Chart
type: application
version: 0.1.0
home: https://github.com/validatedpatterns/ztwim-chart
maintainers:
  - name: Validated Patterns Team
    email: validatedpatterns@googlegroups.com
