---
compact: true
directory:
  - .
skip-path:
  - tests
skip-check:
  # CKV_K8S_49: Minimize wildcard use in Roles and ClusterRoles
  - CKV_K8S_49
  # CKV_K8S_155: ClusterRoles for admission webhook configurations
  - CKV_K8S_155
  # CKV_K8S_156: ClusterRoles to approve CertificateSigningRequests
  - CKV_K8S_156
  # CKV_K8S_157: Roles/ClusterRoles to bind RoleBindings or ClusterRoleBindings
  - CKV_K8S_157
  # CKV_K8S_158: Roles/ClusterRoles to escalate Roles or ClusterRoles
  - CKV_K8S_158
